# Generated by Django 5.1.1 on 2024-11-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='prosucts/%y/%m/%d/'),
        ),
    ]
