# Generated by Django 5.1.1 on 2024-12-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaible',
            new_name='available',
        ),
    ]
