# Generated by Django 5.1.1 on 2024-12-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descreption',
            new_name='description',
        ),
    ]
