# Generated by Django 5.1.1 on 2025-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category_is_sub_category_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='scategory', to='home.category'),
        ),
    ]
